<h1> Hello, Welcome to Valaxy Technologies !!! </h1>
<h2> Deploying on Kubernetes </h2>
<h3> WAY TO GO WITH CONTAINER AND KUBERNETES </h3>
<h3> OH YAAAA CREATE BUILD AND MOVED THORUGH ANSIBLE </h3>
<h3> OH YAAAA CREATE BUILD AND DEPLOYED THROUGH CONTAINE AKA DOCKER </h3>
<h3> OH YAAAA CREATE BUILD AND DEPLOYED THROUGH CONTAINE AKA DOCKER AND IMAGE PUSHED TO DOCKER HUB </h3>
